[package]
name = "rasptank-plain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#bonsai-bt = "0.4.9"
#linux-embedded-hal = "0.3.2"
#mpu6050 = "0.1.6"
#pwm-pca9685 = "0.3.1"
rs_ws281x = "0.4.4"
